### ISSUE TITLE
Linhas em branco após conteúdo

### ISSUE THREAD

**Issue by jorgedferreira** [amosassis/cfe-printer#3]
Olá, boa tarde. Primeiramente, muitos parabéns pelo trabalho que desenvolveram! 

Estive efetuando uns testes e notei que os PDFs gerados ficam com bastante espaço em branco após o conteúdo. 

Isso é normal?

Obrigado!

**Comment by amosassis** [comment]
Olá, como vai?

Atualmente o tamanho da página está fixo em 1000mm, na prática não interfere na impressão em impressoras de bobina. 

Uma melhoria seria o cálculo do tamanho da página por quantidade de itens.
